apiVersion: v1

kind: ReplicationController

metadata:
  name: myapp-rc
  labels: 
    app: myapp
    type: backend

spec:
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: backend

    spec:
      containers:
      - name: nginx
        image: nginx

  replicas: 2 